version: 2


before:
  hooks:
    - go mod tidy
    - "sed -i.bak 's/\"version\": \".*\"/\"version\": \"{{ .Version }}\"/' plugin.json && rm -f plugin.json.bak"

builds:
  - id: workflow-plugin-datadog
    main: ./cmd/workflow-plugin-datadog
    binary: workflow-plugin-datadog
    env:
      - CGO_ENABLED=0
      - GOPRIVATE=github.com/GoCodeAlone/*
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/GoCodeAlone/workflow-plugin-datadog/internal.Version={{.Version}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
